export const SCREENS = {
    LOBBY: "LOBBY",
    MAIN_MENU: "MAIN_MENU",
    GAME: "GAME",
    SCORE_SCREEN: "SCORE_SCREEN",
    SETTINGS_SCREEN: "SETTINGS_SCREEN"
};

export const HOST_VIEWS = {
    QUESTION_STATEMENT: "QUESTION_STATEMENT",
    GAME_VIEW: "GAME_VIEW",
    CORRECT_ANSWER: "CORRECT_ANSWER",
    ANSWER_STATS: "ANSWER_STATS",
    RANKING: "RANKING",
    RESULTS: "RESULTS",
};
